name: test-suite
description: Run test suite with validation

triggers:
  keywords:
    - "run tests"
    - "test the code"
    - "check tests"

inputs:
  coverage:
    type: boolean
    required: false
    default: false
    description: "Enable coverage reporting"

steps:
  - id: lint
    type: script
    description: Run linter
    run: echo "Running lint..." && sleep 1 && echo "Lint passed"
    validation:
      exit_code: 0

  - id: typecheck
    type: script
    description: Run type checker
    run: echo "Running typecheck..." && sleep 1 && echo "Types OK"
    needs: [lint]
    validation:
      exit_code: 0

  - id: test
    type: script
    description: Run tests
    run: echo "Running tests..." && sleep 2 && echo "All 42 tests passed"
    needs: [typecheck]
    validation:
      exit_code: 0
      stdout_contains: "passed"

settings:
  timeout: 10m
  enforcement: strict
